version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi-todo
    container_name: fastapi-todo
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    ports:
      - "8080:80"

